/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guijava.view;

import java.awt.Color;

/**
 *
 * @author Kevin Ryo Pratama
 */
public class mainView extends javax.swing.JFrame {

    /**
     * Creates new form mainView
     */
    public mainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        btnProduk = new javax.swing.JButton();
        btnPemesanan = new javax.swing.JButton();
        btnTentang = new javax.swing.JButton();
        btnSelesai = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        isiProduk = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        txtUsia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRekomendasi = new javax.swing.JTextField();
        btnTampilkan = new javax.swing.JButton();
        isiTentang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        isiPemesanan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lbAlamat = new javax.swing.JLabel();
        lbNama = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lbPesanan = new javax.swing.JLabel();
        lbHarga = new javax.swing.JLabel();
        btnPesan = new javax.swing.JButton();
        cmbPesanan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnYa = new javax.swing.JButton();
        btnTidak = new javax.swing.JButton();
        lbThanks = new javax.swing.JLabel();
        lbDatang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        headerPanel.setBackground(new java.awt.Color(102, 102, 102));

        Title.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guijava/images/coffeeLogo.png"))); // NOI18N
        Title.setText("                                                   S A P I (Pesan Kopi Online)");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPanel.setBackground(new java.awt.Color(153, 153, 153));

        btnProduk.setBackground(new java.awt.Color(153, 153, 153));
        btnProduk.setText("Produk Kami");
        btnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukActionPerformed(evt);
            }
        });

        btnPemesanan.setBackground(new java.awt.Color(153, 153, 153));
        btnPemesanan.setText("Pemesanan");
        btnPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemesananActionPerformed(evt);
            }
        });

        btnTentang.setBackground(new java.awt.Color(153, 153, 153));
        btnTentang.setText("Tentang Kami");
        btnTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTentangActionPerformed(evt);
            }
        });

        btnSelesai.setBackground(new java.awt.Color(255, 51, 51));
        btnSelesai.setToolTipText("");
        btnSelesai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelesaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelesaiMouseExited(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guijava/images/exitLogo.png"))); // NOI18N
        jLabel2.setText("Selesai");

        javax.swing.GroupLayout btnSelesaiLayout = new javax.swing.GroupLayout(btnSelesai);
        btnSelesai.setLayout(btnSelesaiLayout);
        btnSelesaiLayout.setHorizontalGroup(
            btnSelesaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSelesaiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(26, 26, 26))
        );
        btnSelesaiLayout.setVerticalGroup(
            btnSelesaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSelesaiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPemesanan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProduk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuPanelLayout.createSequentialGroup()
                        .addComponent(btnTentang)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(btnSelesai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnProduk)
                .addGap(59, 59, 59)
                .addComponent(btnPemesanan)
                .addGap(58, 58, 58)
                .addComponent(btnTentang)
                .addGap(198, 198, 198)
                .addComponent(btnSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        isiProduk.setBackground(new java.awt.Color(204, 204, 204));

        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("SELAMAT DATANG DI SAPI!\nBERIKUT PRODUK YANG KAMI SEDIAKAN :\n\n1. Espresso (Rp15.000,-)\n\tEspresso merupakan kopi modern yang paling kuat kadar kopinya.\n\n2. Macchiato (Rp15.000,-)\n\tMacchiato merupakan espresso yang diberi campuran susu foam. \n\tFoam atau susu yang di-steam sendiri kadarnya sedikit, sehingga rasanya tetap strong.\n\n3. Cappucino (Rp15.000,-)\n\tIni dia yang sajian kopi modern yang populer karena mudah ditemui, \n\tbahkan kini tersaji dalam bentuk instan. Cappucino pada dasarnya merupakan \n\tkopi susu yang juga diberi foam.\n\n4. Latte (Rp15.000,-)\n\tSama dengan cappucino, latte pada dasarnya ialah kopi susu. \n\tYang berbeda ialah latte diberi foam dari susu yang sudah di-steam. \n\tKadar susunya paling banyak.");
        jScrollPane2.setViewportView(jTextArea2);

        txtUsia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsiaActionPerformed(evt);
            }
        });

        jLabel6.setText("REKOMENDASI PRODUK! SILAHKAN MASUKKAN USIA ANDA :");

        jLabel7.setText("KOPI REKOMENDASI KAMI : ");

        btnTampilkan.setText("Tampilkan Rekomendasi!");
        btnTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout isiProdukLayout = new javax.swing.GroupLayout(isiProduk);
        isiProduk.setLayout(isiProdukLayout);
        isiProdukLayout.setHorizontalGroup(
            isiProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiProdukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(isiProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, isiProdukLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUsia, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTampilkan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1591, Short.MAX_VALUE))
                    .addGroup(isiProdukLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRekomendasi, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        isiProdukLayout.setVerticalGroup(
            isiProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiProdukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(isiProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnTampilkan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(isiProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtRekomendasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(274, Short.MAX_VALUE))
        );

        mainPanel.add(isiProduk, "card2");

        isiTentang.setBackground(new java.awt.Color(204, 204, 204));

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("SAPI (Pesan Kopi Online) adalah sebuah platform aplikasi yang dibuat dengan tujuan \n\nuntuk memudahkan pencinta kopi untuk memesan kopi kesukaannya dari rumah \n\ntanpa perlu keluar rumah!\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nKevin Ryo Pratama\nPraktikum DKP\n21120119130098");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout isiTentangLayout = new javax.swing.GroupLayout(isiTentang);
        isiTentang.setLayout(isiTentangLayout);
        isiTentangLayout.setHorizontalGroup(
            isiTentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiTentangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2316, Short.MAX_VALUE)
                .addContainerGap())
        );
        isiTentangLayout.setVerticalGroup(
            isiTentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiTentangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        mainPanel.add(isiTentang, "card4");

        jLabel1.setText("Nama Pemesan      :");

        jLabel3.setText("Alamat Pengiriman :");

        jLabel5.setText("Pesanan Kopi         :");

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });

        jLabel32.setText("STRUK PEMESANAN");

        jLabel33.setText("Nama                    :");

        lbAlamat.setText("empty");

        lbNama.setText("empty");

        jLabel37.setText("Pesanan Kopi         :");

        jLabel38.setText("Alamat Pengiriman :");

        lbPesanan.setText("empty");

        lbHarga.setText("-");

        btnPesan.setBackground(new java.awt.Color(0, 255, 204));
        btnPesan.setText("Pesan!");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        cmbPesanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espresso", "Macchiato", "Capuccino", "Latte" }));
        cmbPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPesananActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingin Melakukan Pemesanan Lagi?");

        btnYa.setText("YA");
        btnYa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnYaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnYaMouseExited(evt);
            }
        });
        btnYa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYaActionPerformed(evt);
            }
        });

        btnTidak.setText("TIDAK");
        btnTidak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTidakMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTidakMouseExited(evt);
            }
        });

        lbThanks.setText("-");

        lbDatang.setText("-");

        javax.swing.GroupLayout isiPemesananLayout = new javax.swing.GroupLayout(isiPemesanan);
        isiPemesanan.setLayout(isiPemesananLayout);
        isiPemesananLayout.setHorizontalGroup(
            isiPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiPemesananLayout.createSequentialGroup()
                .addGroup(isiPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, isiPemesananLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, isiPemesananLayout.createSequentialGroup()
                        .addGroup(isiPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(16, 16, 16)
                        .addGroup(isiPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesan)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, isiPemesananLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel32))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, isiPemesananLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(isiPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDatang, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(isiPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(isiPemesananLayout.createSequentialGroup()
                                    .addComponent(jLabel38)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(isiPemesananLayout.createSequentialGroup()
                                    .addComponent(jLabel33)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                    .addComponent(lbNama, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(isiPemesananLayout.createSequentialGroup()
                                    .addComponent(jLabel37)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbThanks, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 1451, Short.MAX_VALUE))
            .addGroup(isiPemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(isiPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(isiPemesananLayout.createSequentialGroup()
                        .addComponent(btnYa)
                        .addGap(59, 59, 59)
                        .addComponent(btnTidak)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        isiPemesananLayout.setVerticalGroup(
            isiPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiPemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(isiPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(isiPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(isiPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cmbPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnPesan)
                .addGap(20, 20, 20)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(isiPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(lbNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(isiPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(lbAlamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(isiPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(lbPesanan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDatang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbHarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbThanks)
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(isiPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnYa)
                    .addComponent(btnTidak))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        mainPanel.add(isiPemesanan, "card4");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemesananActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(isiPemesanan);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnPemesananActionPerformed

    private void btnTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTentangActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(isiTentang);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnTentangActionPerformed

    private void btnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(isiProduk);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnProdukActionPerformed

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void txtUsiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsiaActionPerformed

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
        int usia = Integer.parseInt(txtUsia.getText ());
        if (usia >= 30) {
            txtRekomendasi.setText("Espresso");
        }
        else if (usia >= 20) {
            txtRekomendasi.setText("Macchiato");
        }
        else if (usia > 10) {
            txtRekomendasi.setText("Capuccino");
        }
        else if (usia >= 0 & usia <= 10) {
            txtRekomendasi.setText("Latte");
        }
        else {
            txtRekomendasi.setText("Error");
    }
    }//GEN-LAST:event_btnTampilkanActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        lbNama.setText(Nama.getText());
        lbAlamat.setText(Alamat.getText());
        switch(cmbPesanan.getSelectedIndex()){
            case 0 : lbPesanan.setText("Espresso"); break;
            case 1 : lbPesanan.setText("Macchiato"); break;
            case 2 : lbPesanan.setText("Capuccino"); break;
            case 3 : lbPesanan.setText("Latte"); break;
        }
        lbDatang.setText("Pesanan akan sampai dalam waktu 1 jam.");
        lbHarga.setText("Pembayaran akan dilakukan saat pesanan sudah datang ke rumah Anda!");
        lbThanks.setText("Terima kasih sudah memesan di SAPI! Silahkan simpan bukti struk pembayaran.");
                
    }//GEN-LAST:event_btnPesanActionPerformed

    private void cmbPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPesananActionPerformed

    private void btnYaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYaActionPerformed
        Nama.setText("");
        Alamat.setText("");
        lbNama.setText("");
        lbAlamat.setText("");
        lbPesanan.setText("");
        lbDatang.setText("");
        lbHarga.setText("");
        lbThanks.setText("");
        
    }//GEN-LAST:event_btnYaActionPerformed

    private void btnSelesaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelesaiMouseEntered
        btnSelesai.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnSelesaiMouseEntered

    private void btnSelesaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelesaiMouseExited
        btnSelesai.setBackground (new Color(255,51,51));
    }//GEN-LAST:event_btnSelesaiMouseExited

    private void btnYaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYaMouseEntered
        btnYa.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnYaMouseEntered

    private void btnYaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYaMouseExited
        btnYa.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_btnYaMouseExited

    private void btnTidakMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTidakMouseEntered
        btnTidak.setBackground(Color.RED);
    }//GEN-LAST:event_btnTidakMouseEntered

    private void btnTidakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTidakMouseExited
        btnTidak.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_btnTidakMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField Nama;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnPemesanan;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnProduk;
    private javax.swing.JPanel btnSelesai;
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JButton btnTentang;
    private javax.swing.JButton btnTidak;
    private javax.swing.JButton btnYa;
    private javax.swing.JComboBox<String> cmbPesanan;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel isiPemesanan;
    private javax.swing.JPanel isiProduk;
    private javax.swing.JPanel isiTentang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lbAlamat;
    private javax.swing.JLabel lbDatang;
    private javax.swing.JLabel lbHarga;
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel lbPesanan;
    private javax.swing.JLabel lbThanks;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField txtRekomendasi;
    private javax.swing.JTextField txtUsia;
    // End of variables declaration//GEN-END:variables
}
